### ISSUE TITLE
Multi-keys Indices

### ISSUE THREAD

**Issue by SLMT** [vanilladb/vanillacore#5]
### Motivation

VanillaCore only supports single-key indexes for now. However, most of DBMSs support indexing on multiple keys. There are lots of cases requiring using multi-keys indexes. For example, many DBMSs create an index on primary keys while creating a new table. Primary keys may be combined from a set of keys (or attributes). If we want to index on primary keys, we would need to support multi-keys indexes.

### TODOs

- [x] Survey - which components need to be changed.

**Comment by SLMT** [comment]
Here are the packages which will be changed in plans:

- [ ] query.algebra.index
- [ ] query.parse
- [ ] query.planner.index
- [ ] query.planner.opt
- [ ] sql
- [ ] storage.index
- [ ] storage.index.btree
- [ ] storage.index.hash
- [ ] storage.metadata.index

**Comment by SLMT** [comment]
#27 implements this feature.
